<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://posam.sk/skolenie/service-api" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="ServiceApi" targetNamespace="http://posam.sk/skolenie/service-api">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://posam.sk/skolenie/service-api" targetNamespace="http://posam.sk/skolenie/service-api" version="1.0">

            <xs:element name="zlozityVypis" type="tns:zlozityVypis"/>

            <xs:element name="zlozityVypisResponse" type="tns:zlozityVypisResponse"/>

            <xs:complexType name="zlozityVypis">
                <xs:sequence/>
            </xs:complexType>

            <xs:complexType name="zlozityVypisResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

        </xs:schema>
    </wsdl:types>
    <wsdl:message name="zlozityVypis">
        <wsdl:part element="tns:zlozityVypis" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="zlozityVypisResponse">
        <wsdl:part element="tns:zlozityVypisResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="ServiceApi">
        <wsdl:operation name="zlozityVypis">
            <wsdl:input message="tns:zlozityVypis" name="zlozityVypis">
            </wsdl:input>
            <wsdl:output message="tns:zlozityVypisResponse" name="zlozityVypisResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ServiceApiSoapBinding" type="tns:ServiceApi">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="zlozityVypis">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="zlozityVypis">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="zlozityVypisResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ServiceApi">
        <wsdl:port binding="tns:ServiceApiSoapBinding" name="ServiceApiSOAP">
            <soap:address location="http://localhost:8181/cxf/skolenie"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>